### ISSUE TITLE
Слетела подсветка синтаксиса

### ISSUE THREAD

**Issue by Daruma-ANT** [1c-syntax/vsc-language-1c-bsl#100]
После обновления VS Code до 1.25.0 слетела подсветка синтаксиса файлов BSL (на кириллице, англ. выделяет). Выделяет как-то только комментарии и константы. Как поправить?

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/42647170-db594ff0-860b-11e8-8d4b-bbc842655d71.png)

Не воспроизводится. Откройте инструменты разработчика (dev tools), вкладку консоль (console). есть ли в логах какие-то сообщения?

**Comment by Daruma-ANT** [comment]
---WBW, Анатолий Змиевский

**Comment by petypen** [comment]
У меня такое же поведение. Подсветки нет.
Код 1С написан для платформы 7.7.
версия плагина 1.11.1
Консоль пустая.
Все началось после обновления VSC на 1.25
![2018-07-13 09-24-45 bsl - frontol - visual studio code](https://user-images.githubusercontent.com/6500075/42676053-385db86c-867f-11e8-92b8-55da0c8c1a8f.png)
![2018-07-13 09-26-03 bsl - frontol - visual studio code](https://user-images.githubusercontent.com/6500075/42676056-3a549244-867f-11e8-888d-a854e66a6f9b.png)

**Comment by petypen** [comment]
[МодульФормы.zip](https://github.com/1c-syntax/vsc-language-1c-bsl/files/2191529/default.zip)
файл для примера

**Comment by Daruma-ANT** [comment]
![2018-07-12_22-03-46](https://user-images.githubusercontent.com/20789648/42676613-86a5b842-8681-11e8-90ea-bf64d2467fcb.png)
Консоль инструмента разработчика

**Comment by petypen** [comment]
К сожалению в инсайдер версии тот же результат

![2018-07-30 18-29-53 1s - frontol - visual studio code - insiders](https://user-images.githubusercontent.com/6500075/43407198-bc5ca434-9426-11e8-93c4-ffcb46c37466.png)

**Comment by petypen** [comment]
Заметил, что англоязычные наименования операторов подсвечивает а русскоязычные нет

![2018-07-30 18-35-59 objectmodule bsl - src - visual studio code](https://user-images.githubusercontent.com/6500075/43407443-7601c00e-9427-11e8-9825-be9d814f1ca5.png)

**Comment by nixel2007** [comment]
win1251?

**Comment by petypen** [comment]
Если код от 1с 7.7  то да (черный скрин) Если 1с 8 то utf8 (светлый скрин)18:58, 30 июля 2018 г., Nikita Gryzlov <notifications@github.com>:win1251?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

С уважением Евгений.

**Comment by bambr1975** [comment]
А какие плагины подключены? И какие настройки в файле settings.json ? Если на время почистить папку extensions, оставив там только xDrivenDevelopment.language-1c-bsl-1.11.1  будет то же самое? У меня тоже подключен scope-bar и magic python, и в файловых ассоциациях стоит `"*.1s": "bsl"` и vs code обновлен до последней версии, но подсветка работает. Еще, @petypen, если можно, сделайте тоже скрин консоли разработчика (Справка - Показать/скрыть средства разработчика).

**Comment by nixel2007** [comment]
@bambr1975 обрати внимание - UTF-8 with BOM

**Comment by bambr1975** [comment]
@nixel2007 это тоже не воспроизводится. И Win1251 и UTF-8 with BOM нормально подсвечиваются

**Comment by bambr1975** [comment]
@Daruma-ANT  @petypen , изменилась ли ситуация с выходом 1.26 ?

**Comment by petypen** [comment]
Аллилуйя! В 1.26 все работает. Тикет можно закрывать.
