### ISSUE TITLE
Сортировка кода

### ISSUE THREAD

**Issue by arXXXimed** [1c-syntax/vsc-language-1c-bsl#117]
Возможно ли сделать сортировку процедур или функций по наименованию?

**Comment by nixel2007** [comment]
Сейчас нет. А зачем?

**Comment by bambr1975** [comment]
![image](https://user-images.githubusercontent.com/9781644/46792796-d801b800-cd4c-11e8-886f-05c3f46b0b74.png)
Вы об этом?

**Comment by arXXXimed** [comment]
> Вы об этом? @arXXXimed

Нет, не об этом. Но это штука очень помогает, Спасибо @bambr1975 

--------------------
@nixel2007 
> Сейчас нет. А зачем?

В VS code, чаще анализирую и исправляю достаточно объемный код.
Собственно и пришлось редактировать модуль с 70+ однотипных процедур, которые отличаются мелочами. Вот и возник вопрос как их отсортировать.

В принципе задача достаточно редкая.. Но все же возникла

**Comment by nixel2007** [comment]
Пока не вижу глобальной надобности для этой фичи в плагине.
