### ISSUE TITLE
Сворачивание блока комментария в заголовке процедур и функций

### ISSUE THREAD

**Issue by zhilichev** [1c-syntax/vsc-language-1c-bsl#121]
Возможно ли реализовать сворачивание блока комментария в заголовках методов? По аналогии с редактором 1С.

![image_000223](https://user-images.githubusercontent.com/6815305/48879396-3a270000-ee57-11e8-9c80-6807163c3523.png)

![image_000224](https://user-images.githubusercontent.com/6815305/48879420-588cfb80-ee57-11e8-8f8b-f0b67e427086.png)

**Comment by nixel2007** [comment]
Добрый, день, да, возможно.

**Comment by nixel2007** [comment]
В основной репе 1с-синтакс даже есть уже задачка на это дело :)
Так что здесь закрываю.
