### ISSUE TITLE
Дублирование комментария вначале файла

### ISSUE THREAD

**Issue by grumagargler** [1c-syntax/vsc-language-1c-bsl#135]
День добрый!
Если вначале bsl-файла присутствует комментарий, при записи такого файла, этот комментарий дублируется.
Способ воспроизведения:
- создать и сохранить новый bsl-файл
- ввести первой строкой: // test
- нажать enter
- нажать ctrl+s
После этого - в файле будет две строки // test
Спасибо!
---
1.13.0

**Comment by nixel2007** [comment]
Добрый день.

Подскажите, включено ли форматирование файла при сохранении?

**Comment by nixel2007** [comment]
Исправлено в 1.14.0
