### ISSUE TITLE
Не стартует bsl 

### ISSUE THREAD

**Issue by shalimski** [1c-syntax/vsc-language-1c-bsl#136]
[Info  - 8:16:40] Connection to server got closed. Server will restart.
[Info  - 8:16:40] Connection to server got closed. Server will restart.
[Info  - 8:16:40] Connection to server got closed. Server will restart.
[Info  - 8:16:41] Connection to server got closed. Server will restart.
[Error - 8:16:41] Connection to server got closed. Server will not be restarted.

Куда копать?

**Comment by nixel2007** [comment]
Добрый день. Какая версия плагина?

**Comment by shalimski** [comment]
Сейчас 1.14.0, на 1.13 была такая же ошибка.

**Comment by asosnoviy** [comment]
'java -jar C:\Users\%username%\.vscode\extensions\xdrivendevelopment.language-1c-bsl-1.14.0\languageserver\bsl-language-server.jar -h' что то говорит?

**Comment by shalimski** [comment]
java -jar C:\Users\%username%\.vscode\extensions\xdrivendevelopment.language-1c-bsl-1.14.0\languageserver\bsl-language-server.jar -h
usage: BSL language server [-a] [-c <arg>] [-h] [-o <arg>] [-r <arg>] [-s
       <arg>]
 -a,--analyze               Run analysis and get diagnostic info
 -c,--configuration <arg>   Path to language server configuration file
 -h,--help                  Show help.
 -o,--outputDir <arg>       Output report directory
 -r,--reporter <arg>        Reporter key
 -s,--srcDir <arg>          Source directory

**Comment by nixel2007** [comment]
Настройки плагина по дефолту? Не переопределяли пути к джаве или лэнг серверу? Дополнительные параметры какие-нибудь?

**Comment by nixel2007** [comment]
Сколько оперативной памяти на машине? Сколько свободной памяти?

**Comment by shalimski** [comment]
Настройки плагина по дефолту, переустановка плагина также не помогает.
Память: свободно 3 из 8.
В редакторе 1 открытый файл на 10 строк.
java version "1.8.0_211"

**Comment by nixel2007** [comment]
Хм...
Имя пользователя в винде?

**Comment by shalimski** [comment]
латиницой, без пробелов

**Comment by nixel2007** [comment]
Так... Открываете отдельный файл или каталог?

**Comment by nixel2007** [comment]
О, точка. Дело может быть в ней, посмотрю.

**Comment by shalimski** [comment]
Отдельный файл...
Открываю vscode, в новый документ вставляю кусок кода, меняю язык на BSL - вываливает ошибки.

**Comment by shalimski** [comment]
Рядом сидит коллега - у него тоже точка и все работает.

**Comment by asosnoviy** [comment]
> О, точка. Дело может быть в ней, посмотрю.

Я тоже с точкой. Вряд ли в ней.

**Comment by nixel2007** [comment]
Частично воспроизвел. Проблема в открытии VSCode в режиме "файла". откройте "каталог" и проблема уйдет. а над фиксом мы поработаем, спасибо!

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/58458032-c846b080-8130-11e9-9202-5133d1e0079b.png)

**Comment by shalimski** [comment]
Я сделал каталог, сохранил туда файл, добавил его в воркспейс - проблема не ушла.

**Comment by nixel2007** [comment]
я имею ввиду открытие каталога через File -> Open folder.
VSC по-разному работает в режимах file -> open file и open folder.

**Comment by shalimski** [comment]
Нет, так тоже не помогло.

**Comment by nixel2007** [comment]
[languageClientProvider.zip](https://github.com/1c-syntax/vsc-language-1c-bsl/files/3226156/languageClientProvider.zip)

попробуйте заменить этот файл в out/src/features, пожалуйста.

**Comment by shalimski** [comment]
Заменил, не помогло

**Comment by nixel2007** [comment]
Путь к рабочему каталогу содержит пробелы?

**Comment by nixel2007** [comment]
окей, копнем шире - версия ОС? версия vscode?

**Comment by shalimski** [comment]
Винда 7ка. Microsoft Windows x64 [Version 6.1.7601]. vscode 1.34.0

**Comment by arXXXimed** [comment]
Точно такая же проблема...

**Comment by asosnoviy** [comment]
> Точно такая же проблема...
> Изначально писала, что нету доступа к java
> Установил java se
> После этого начало писать о невозможности запустить сервер bsl
 
`java -version`
`java -jar %userprofile%\.vscode\extensions\xdrivendevelopment.language-1c-bsl-1.15.0\languageserver\bsl-language-server.jar -v`

Что говорят?

**Comment by arXXXimed** [comment]
> > Точно такая же проблема...
> > Изначально писала, что нету доступа к java
> > Установил java se
> > После этого начало писать о невозможности запустить сервер bsl
> 
> `java -version`
> `java -jar %userprofile%\.vscode\extensions\xdrivendevelopment.language-1c-bsl-1.15.0\languageserver\bsl-language-server.jar -v`
> 
> Что говорят?

PS C:\Windows\system32> java -jar c:\Users\ARXIMED\.vscode\extensions\xdrivendevelopment.language-1c-bsl-1.15.0\languageserver\bsl-language-server.jar -v
version: 0.8.0

PS C:\Windows\system32> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)

**Comment by asosnoviy** [comment]
> C:\Windows\system32>
выглядит как будто cmd запущен под админом. Под пользователем такой же выхлоп?

**Comment by arXXXimed** [comment]
Я не понял что сделал... Но все резко заработало ))))

**Comment by asosnoviy** [comment]
@shalimski после апдейта плагина стало лучше?

**Comment by arXXXimed** [comment]
> @shalimski после апдейта плагина стало лучше?

Так вроде проблема и была на 1.15.0

**Comment by shalimski** [comment]
> @shalimski после апдейта плагина стало лучше?

Нет, проблема осталась

**Comment by shalimski** [comment]
Поставил openjdk 11 - проблема ушла.

> openjdk version "11.0.2" 2019-01-15
> OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by nixel2007** [comment]
У коллеги похожая проблема решилась переустановкой jdk8. Возможно что-то не так с path, но пока не получается понять, что именно :(

**Comment by froloid** [comment]
У меня такая же история. jdk8 переустановил. Запуск jar файла сервера выводит версию:

> C:\Users\froloid>java -jar d:\fdi\vscode\data\extensions\xdrivendevelopment.language-1c-bsl-1.16.0\languageserver\bsl-language-server.jar -v
version: 0.9.1

При этом плагин для VSC частично работает: есть раскраска и сгруппированы блоки, процедуры и функции. Но нет дерева методов в панеле outline (а когда-то точно было), не срабатывает комбинация клавиш для работы со списком методов. А этих функций очень не хватает.

**Comment by nixel2007** [comment]
@froloid как временное решение - отключите в настройках использование bsl ls.

**Comment by froloid** [comment]
> @froloid как временное решение - отключите в настройках использование bsl ls.

Спасибо - сработало. А для чего он в плагине используется (что я потерял бы если бы он работал, а я отключил)?

**Comment by nixel2007** [comment]
@froloid через него сейчас работает сворачивание процедур/функций/областей/блоков кода - умнее, чем просто в плагине, т.к. просто плагин работает на основе отступов.

outline в плагине не умеет показывать дерево областей и переменные, плюс методы он показывает только по заголовку, не позиционируется на имя процедуры, не делает выделения.

форматтер в BSL LS на мой взгляд предсказуемее. Но тут фактор "фатального недостатка", форматтер в bsl ls писал я, а в плагине - @bambr1975 :)

без BSL LS не работают диагностики.

в целом можно сказать, что все новые фичи и улучшение старых будет реализовано только в BSL LS, поэтому было бы здорово джаву таки починить. 

плюс мы ищем пути по standalone-запуску BSL LS, которому бы не требовалась джава, но пока это... в планах :)

**Comment by froloid** [comment]
@nixel2007 

> джаву почнить

Это в смысле у меня что-то не так с установкой? Или это в самом jdk что-то не так?

**Comment by nixel2007** [comment]
@froloid скорее у вас.

Понимаете, какой момент. Среди сотен пользователей не работает только у... четырех, известных мне. То есть явно какая-то загвоздка с окружением.

Это все очень грустно, конечно же, но я правда не знаю, почему не работает и идеи, почему может не работать, тоже закончились. Осложняется еще все тем, что я не могу это воспроизвести =/

Постараюсь добавить больше логов при неудачном запуске, может быть что-то можно будет отловить по ним.

**Comment by froloid** [comment]
@nixel2007 Никита, если есть желание и время разобраться, могу предоставить доступ своей машине. Если интересно, то дальше через личку.

**Comment by nixel2007** [comment]
@froloid желание есть, спасибо!
Буду иметь ввиду

**Comment by bopoh13** [comment]
@nixel2007, подскажите, пожалуйста. Существовал ли BSL LS x86 или лучше отключить его на 32 bit машине? `"editor.guides.bracketPairs": false,`
> java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) Client VM (build 25.333-b02, mixed mode, sharing)

Как бы пощупать https://github.com/otymko/phoenixbsl, пока нет возможности попробовать 1С: EDT

**Comment by nixel2007** [comment]
bsl ls можно запустить на x86, но нужна java 11 и соответственно запуск из external jar, а не родное пакетирование в zip
