### ISSUE TITLE
Издатель  - ребрендинг

### ISSUE THREAD

**Issue by allustin** [1c-syntax/vsc-language-1c-bsl#143]
Сейчас в marketplace в качестве издателя числится

![изображение](https://user-images.githubusercontent.com/55323/59556665-d456bd00-8fce-11e9-864b-3e18b65b23a8.png)

Что указывает на 

![изображение](https://user-images.githubusercontent.com/55323/59556666-dde02500-8fce-11e9-87c3-6797a1c52f28.png)

А ссылка ведет а репозиторий другой организации

Я так понимаю произошел ребрендинг и использование шильдика организации xDrivenDevelopment уже не актуально.

Нужно сменить издателя.

**Comment by nixel2007** [comment]
Не вижу в админке маркетплейса каких-либо настроек у издателя. напишу им в саппорт с соответствующим вопросом.
