### ISSUE TITLE
Если не установлена java - предложить установить

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/vsc-language-1c-bsl#156]
![image](https://user-images.githubusercontent.com/729213/63057938-17141300-bef4-11e9-96db-703749558501.png)

**Comment by nixel2007** [comment]
> предложить установить

каким образом?

**Comment by bambr1975** [comment]
Мы же можем выводить ссылку в сообщении? И отправлять по адресу https://jdk.java.net/archive/ (если я ничего не путаю)

**Comment by zeegin** [comment]
То, что нет явы - это не ошибка. Это не задействование возможностей.
Надо предложить: "Хотите использовать расширенные возможности редактирования и бла бла бла 1С кода? Установите яву, и предложить ссылку или отказаться от предложения.

**Comment by JAGUAR-90210** [comment]
Увидел сообщение про java пошел сюда.
Бегло пробежал по описанию,  нету информации какая версия java необходима.
про ссылку или короткое описание что нужно сделать. 
Как новенькому тяжело понять, ошибка это или нужно для расширений возможностей?

**Comment by nixel2007** [comment]
@Jaguar-90210

Добрый день. В чейнджлогах к плагину было написано, что нужна минимум 8 джава, но в основной документации про это действительно нет. Подойдут и оракловые сборки и, например, adoptopenjdk или libericajdk. 

Джава используется для запуска BSL Language Server, на который переводится функциональность данного расширения + появляются дополнительные плюшки вроде умного сворачивания групп, диагностик и прочего, описанного на https://1c-syntax.github.io/bsl-language-server 

На данный момент установка джавы настоятельно рекомендуется для "более полного экспириенса" (с)

**Comment by arXXXimed** [comment]
Очень не хватает предложения по установке java. я как новичок который хотел бы отфарматировать только код 1С, и установил это расширение, не знаю как и где устанавливать. Хоть бы где на главное странице было указано ... с инструкцией

**Comment by nixel2007** [comment]
@arXXXimed последний релиз плагина для vsc уже не требует установки java, только интернет для скачивания образа с bsl ls.

**Comment by zeegin** [comment]
Закрываем?
