### ISSUE TITLE
Вопрос по линтеру

### ISSUE THREAD

**Issue by ProgED** [1c-syntax/vsc-language-1c-bsl#170]
Большое вам человеческое спасибо за то, что вы делаете!

Скажите, а можно ли как-нибудь донастроить линтер под себя?

**Comment by nixel2007** [comment]
Спасибо за отзыв!

Если речь про диагностики, которые появляются в последних релизах и идут от BSL LS, то да, их можно настроить с помощью конфигурационного файла:

https://1c-syntax.github.io/bsl-language-server/#configuration

по умолчанию плагин ищет файл в корне проекта по имени `.bsl-language-server.json` (обратите внимание на точку в начале)

**Comment by ProgED** [comment]
Спасибо! Помогло ))
