### ISSUE TITLE
Нет задач в списке

### ISSUE THREAD

**Issue by MStepanov55** [1c-syntax/vsc-language-1c-bsl#172]
Добрый день! 
После установки создал файл с расширением .os
Нажал F1 и выбрал Tasks: Run Task
В списке нет ни одной задачи для выполнения.
Подскажите что нужно настроить, чтобы появились задачи?

![image](https://user-images.githubusercontent.com/58200561/70819344-d4a60880-1df7-11ea-90f6-f4346efc9f9c.png)

**Comment by nixel2007** [comment]
Запуск задач сейчас проще всего выполнять с помощью расширения OneScript Debug - отладчика OneScript

**Comment by MStepanov55** [comment]
Получилось, код выполняется. Спасибо @nixel2007 !

> Запуск задач сейчас проще всего выполнять с помощью расширения OneScript Debugger - отладчика OneScript
