### ISSUE TITLE
Не работает используемая в документации ссылка

### ISSUE THREAD

**Issue by pimchest** [1c-syntax/vsc-language-1c-bsl#209]
![image](https://user-images.githubusercontent.com/32355274/84897453-4401fb00-b0ae-11ea-8064-8e9779e7af0e.png)

Ссылка на страницу документации:
[https://github.com/1c-syntax/vsc-language-1c-bsl/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-BSL-Language-Server](url)

**Comment by nixel2007** [comment]
Поправил, спасибо.
