### ISSUE TITLE
Зависает установка BSL LS из плагина.

### ISSUE THREAD

**Issue by 240596448** [1c-syntax/vsc-language-1c-bsl#217]
В виде костыля придумать таймаут распаковки.

Ловил зависания и на Windows(s2019), и на Линукс(Ubuntu).
Zip полностью распаковывался, но не формировался файл SERVER-INFO.
После создания файла руками сервер работает корректно.

**Comment by zhilichev** [comment]
> SERVER-INFO
> После создания файла руками сервер работает корректно.
Подскажите как это сделать?

**Comment by 240596448** [comment]
> > SERVER-INFO
> > После создания файла руками сервер работает корректно.
> 
> Подскажите как это сделать?

Положить сюда `c:\Users\myuser\AppData\Roaming\Code\User\globalStorage\1c-syntax.language-1c-bsl\bsl-language-server\`
или сюда `\home\myuser\.vscode-server\data\User\globalStorage\1c-syntax.language-1c-bsl\bsl-language-server\`
SERVER-INFO с содержимым
`{"version":"v0.16.2","lastUpdate":1603533797606}`
(как я понимаю, последние цифры большого значения в данном случае не имеют)

**Comment by nixel2007** [comment]
Проблема должна быть исправлена в последнем релизе плагина.
