### ISSUE TITLE
Бесконечная распаковка BSL Language Server

### ISSUE THREAD

**Issue by forkmalik** [1c-syntax/vsc-language-1c-bsl#218]
При установки Language 1C (BSL) из Раcширений VS Code не прекращается распаковка BSL Language Server v0.16.2
![Screenshot_1](https://user-images.githubusercontent.com/55617080/96866898-aa3fc580-1474-11eb-8b1e-31df52f9c393.png)

**Comment by nixel2007** [comment]
Да, знаем о проблеме. Спасибо за репорт.
https://github.com/1c-syntax/vsc-language-1c-bsl/issues/217
