### ISSUE TITLE
Ошибка в VSC "BSL LS base install dir contains cyrillic letters"

### ISSUE THREAD

**Issue by sulfur17** [1c-syntax/vsc-language-1c-bsl#225]
В Visual Studio Code постоянно всплывает окно:

BSL LS base install dir <c:\Users\Дмитрий\AppData\Roaming\Code\User\globalStorage\1c-syntax.language-1c-bsl> contains cyrillic letters.
                Please override language-1c-bsl.languageServerBaseInstallDir setting and set directory without cyrillic like "c:\tools\BSL Language Server"

**Comment by nixel2007** [comment]
Добрый день. В этом же окне написано, что нужно сделать :) Это не ошибка, это наоборот защита от некорректной работы.

**Comment by sulfur17** [comment]
@nixel2007 он пишет что надо перенести директорию установки если я правильно понял. Но как это сделать? Ее же потом надо где-то в настройках прописать?
Кроме того у меня вообще нет файла/папки c:\Users\Дмитрий\AppData\Roaming\Code\User\globalStorage\1c-syntax.language-1c-bsl
В папке c:\Users\Дмитрий\AppData\Roaming\Code\User\globalStorage\ лежит только два файла state.vscdb и state.vscdb.backup
Я в растерянности, совершенно не понимаю куда копать(

**Comment by nixel2007** [comment]
@sulfur17 

>  Но как это сделать? Ее же потом надо где-то в настройках прописать?

File -> Preferences -> Settings. Внутри Extensions -> Language (1C) BSL. и найти там Language Server Base Install dir.

> Кроме того у меня вообще нет файла/папки...

Плагин ее не создает, т.к. не сможет ее потом использовать (особенность работы скомпилированных джава-приложений под виндой).

**Comment by bopoh13** [comment]
Найдена директория установки сервера BSL Language Server по умолчанию в v1.26, только переменную среды `%APPDATA%` расширение не понимает. Настройка ниже
`"language-1c-bsl.languageServerBaseInstallDir": "${env:APPDATA}\\Code\\User\\globalStorage\\1c-syntax.language-1c-bsl",`
