### ISSUE TITLE
ключевое слово Затем не выделяется цветом

### ISSUE THREAD

**Issue by sulfur17** [1c-syntax/vsc-language-1c-bsl#227]
![image](https://user-images.githubusercontent.com/4643260/116729463-d9209080-a9ef-11eb-92bc-0c998f3a7b77.png)

**Comment by otymko** [comment]
@sulfur17 А для подсветки языка геркин какой плагин у вас используется?

**Comment by bambr1975** [comment]
но мы можем подсказать, какой плагин поддерживает ключевое слово "Затем"
![image](https://user-images.githubusercontent.com/9781644/116740210-5a325480-a9fd-11eb-9f0d-adb047d0eb1a.png)
