### ISSUE TITLE
Переименование (Rename F2) недоступно

### ISSUE THREAD

**Issue by dmipec** [1c-syntax/vsc-language-1c-bsl#258]
Как так!? 
Все подчеркивает, все красиво.
А переименовать переменную нельзя!
Самая распространенная фича.
Кто подскажет?

**Comment by asosnoviy** [comment]
В девелопе уже должно быть

**Comment by nixel2007** [comment]
> В девелопе уже должно быть

если быть точным - в prerelease-канале bsl ls.
