### ISSUE TITLE
Не подсвечивает синтаксис в языке запросов 1С

### ISSUE THREAD

**Issue by coderones** [1c-syntax/vsc-language-1c-bsl#273]
Не подсвечивает синтаксис в языке запросов 1С.

![query](https://github.com/1c-syntax/vsc-language-1c-bsl/assets/150936835/3e6d585a-dbf9-4297-ab50-26f6cde96ac0)

![vsc](https://github.com/1c-syntax/vsc-language-1c-bsl/assets/150936835/993bffe6-d182-42ab-8ffd-62c0ff91f899)

**Comment by nixel2007** [comment]
Добрый день. Какой язык выбрал?

**Comment by coderones** [comment]
> Какой язык выбран?

Добрый день. 

Смотря где.  Про что Вы спрашиваете?
Например, интерфейс Visual Studio Code - русский, в расширении Language 1C (BSL) configuratuion, в параметре Language Autocomplete , - ru.

Файл, с текстом запроса, имеет расширение "os", пробовал с расширением "bsl" - не помогло.

**Comment by nixel2007** [comment]
В прямом нижнем углу
