### ISSUE TITLE
Размещение плагина в open-vsx.org

### ISSUE THREAD

**Issue by Kirill** [1c-syntax/vsc-language-1c-bsl#274]
Для установки плагина в VSCodium необходима его публикация в отдельном маркетплейсе https://open-vsx.org/

**Comment by WonderMr** [comment]
Пока есть только такие костыли:
1. https://milicendev.netlify.app/article/install-vs-codium-and-integrate-vs-code-extensions/
2. https://github.com/OliverKeefe/vscode-extensions-in-vscodium

**Comment by nixel2007** [comment]
Готово. https://open-vsx.org/extension/1c-syntax/language-1c-bsl
