### ISSUE TITLE
Auto indent on type, move lines and paste

### ISSUE THREAD

**Issue by JohnyDeath** [1c-syntax/vsc-language-1c-bsl#58]
В VSC появилась, как мне кажется, очень удобная штука:
https://code.visualstudio.com/updates/v1_14#_auto-indent-on-type-move-lines-and-paste

Можно дополнить bsl такими правилами?

**Comment by nixel2007** [comment]
Issue moved to [1c-syntax/1c-syntax #301](https://github.com/1c-syntax/1c-syntax/issues/301) via [**ZenHub**](https://www.zenhub.com/)
